version: '3.1'
services:    
    db-mongo:
      container_name: db-mongo
      image: mongo:4.4.5
      restart: always
      ports:
          - "27017:27017"
          - "27018:27018"
      environment:
          - MONGO_INITDB_ROOT_USERNAME=pessoal
          - MONGO_INITDB_ROOT_PASSWORD=123456
          - MONGO_INITDB_DATABASE=zedelivery
      volumes:
         - ./data-principal:/data/db

